---
  - name: Update user
    become: true
    user:
      name: "{{ USER }}"
      groups: video
      append: true

  - name: Install Python3
    become: true
    package:
      name: python3
      state: present

  - name: Install pip
    become: true
    package:
      name: python3-pip
      state: present

  - name: Install virtualenv
    become: true
    package:
      name: virtualenv
      state: present
