---
  - name: Update user
    become: true
    user:
      name: "{{ USER }}"
      groups: video
      append: true

  - name: Install Python3
    become: true
    package:
      name: python3
      state: present

  - name: Install pip
    become: true
    package:
      name: python3-pip
      state: present

  - name: Install virtualenv
    become: true
    package:
      name: virtualenv
      state: present

  - name: Install fswebcam
    become: true
    package:
      name: fswebcam
      state: present

  - name: Install exiftool
    become: true
    package:
      name: exiftool
      state: present

  - name: Create app directory
    become: true
    file:
      path: "{{ TIMELAPSE_HOME }}"
      state: directory
      owner: "{{ USER }}"

  - name: Copy timelapse.py to directory
    copy:
      src: "{{ LOCAL_TIMELAPSE_HOME }}/timelapse.py"
      dest: "{{ TIMELAPSE_HOME }}"
      owner: "{{ USER }}"

  - name: Copy timelapse config.yml to directory
    copy:
      src: "{{ LOCAL_TIMELAPSE_HOME }}/sample_config.yml"
      dest: "{{ TIMELAPSE_HOME }}/config.yml"
      owner: "{{ USER }}"

  - name: Copy requirements.txt to directory
    copy:
      src: "{{ LOCAL_TIMELAPSE_HOME }}/requirements.txt"
      dest: "{{ TIMELAPSE_HOME }}"
      owner: "{{ USER }}"

  - name: Install virtualenv requirements
    pip:
      requirements: "{{ TIMELAPSE_HOME }}/requirements.txt"
      virtualenv: "{{ TIMELAPSE_HOME }}/venv"
      virtualenv_python: python3
