---
  - name: Update user
    become: true
    user:
      name: "{{ USER }}"
      groups: video
      append: true

  - name: Install imagemagick
    become: true
    package:
      name: imagemagick
      state: present

  - name: Install ffmpeg
    become: true
    package:
      name: ffmpeg
      state: present

  - name: Create app directory
    become: true
    file:
      path: "{{ TIMELAPSE_GEN_HOME }}"
      state: directory
      owner: "{{ USER }}"

  - name: Create video out directory
    become: true
    file:
      path: "{{ TIMELAPSE_GEN_VIDEO }}"
      state: directory
      owner: "{{ USER }}"

  - name: Copy timelapse.py to directory
    copy:
      src: "{{ LOCAL_TIMELAPSE_GEN_HOME }}/timelapse_gen.py"
      dest: "{{ TIMELAPSE_GEN_HOME }}"
      owner: "{{ USER }}"

  - name: Copy timelapse config.yml to directory
    copy:
      src: "{{ LOCAL_TIMELAPSE_GEN_HOME }}/sample_timelapse_gen_config.yml"
      dest: "{{ TIMELAPSE_GEN_HOME }}/config.yml"
      owner: "{{ USER }}"

  - name: Copy requirements.txt to directory
    copy:
      src: "{{ LOCAL_TIMELAPSE_GEN_HOME }}/requirements.txt"
      dest: "{{ TIMELAPSE_GEN_HOME }}"
      owner: "{{ USER }}"

  - name: Install virtualenv requirements
    pip:
      requirements: "{{ TIMELAPSE_GEN_HOME }}/requirements.txt"
      virtualenv: "{{ TIMELAPSE_GEN_HOME }}/venv"
      virtualenv_python: python3
