timelapses:
  - name:         test_timelapse_480
    src_dir:      /srv/timelapse/photos
    out_dir:      /srv/timelapse_gen/videos
    out_tmp_dir:  /tmp/timelapse_tmp/
    fps:          24
    resolution:   852x480
